title: Site

columns:
  - width: 1/3
    sections:
      albums: sections/questions
  - width: 1/3
    sections:
      notes: sections/notices
      pages:
        type: pages
        template:
          - about
          - home
          - default
          - notices
  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          featurednotice:
            label: Featured notice
            type: select
            options: query
            query: site.grandchildren.published
