title: Site

columns:
  - width: 1/2
    sections:
      pages: 
        type: pages
        layout: cards
      
      subpages:
        extends: sections/subpages

  - width: 1/2
    sections:
      notices:
        extends: sections/notices